---
# tasks file for ansible-manage-aix-lvm
- include: aix_lvm_build.yml
  tags: build
  when: >
    manage_lvm and
    vglist is defined

- include: aix_lvm_modify.yml
  tags: modify
  when: >
    manage_lvm and
    vglist is defined

- include: aix_lvm_remove.yml
  tags: remove
  when: >
    manage_lvm and
    vglist is defined