---
# tasks file for ansible-manage-aix-lvm
- include_tasks: aix_lvm_build.yml
  tags: build
  when:
    - manage_lvm
    - vglist is defined

- include_tasks: aix_lvm_modify.yml
  tags: modify
  when:
    - manage_lvm
    - vglist is defined

- include_tasks: aix_lvm_remove.yml
  tags: remove
  when:
    - manage_lvm
    - vglist is defined

- name: Register that this role has run
  set_fact: aix_lvm_has_run=true
  when: aix_lvm_has_run is not defined